---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ (splitList "/" .Values.deployment.fsaApi.imageName) | last }}  
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ (splitList "/" .Values.deployment.fsaApi.imageName) | last }}-apps
    app: {{ (splitList "/" .Values.deployment.fsaApi.imageName) | last }}
    version: v1    
spec:
  replicas: {{ .Values.deployment.fsaApi.replicaCount }}
  selector:
    matchLabels:
      app: {{ (splitList "/" .Values.deployment.fsaApi.imageName) | last }}
      version: v1
  template:
    metadata:
      labels:
        app: {{ (splitList "/" .Values.deployment.fsaApi.imageName) | last }}
        version: v1
      annotations:
        sidecar.istio.io/extraStatTags: destination_port,request_host,request_path,request_url_path,request_method,request_headers,request_referer,request_useragent,request_query,request_client_ip                
    spec:
      serviceAccountName: {{ .Values.deployment.fsaApi.serviceAccountName }} 
      containers:
        - name: {{ (splitList "/" .Values.deployment.fsaApi.imageName) | last }}-app
          image: {{ .Values.deployment.fsaApi.imageName }}:{{ .Values.deployment.fsaApi.imageTag }}
          imagePullPolicy: {{ .Values.deployment.fsaApi.imagePullPolicy }}                              
          env:        
            - name: PORT
              value: "{{ .Values.deployment.fsaApi.containerPort }}"          
          {{- range $key, $val := .Values.deployment.fsaApi.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
          {{- end }}                                                  
          ports:
            - containerPort: {{ .Values.deployment.fsaApi.containerPort }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.deployment.fsaApi.containerPort }}
            initialDelaySeconds: 5
            periodSeconds: 10          
          livenessProbe:
            httpGet:
              path: /liveness
              port: {{ .Values.deployment.fsaApi.containerPort }}
            initialDelaySeconds: 5
            periodSeconds: 60
          {{- with .Values.deployment.fsaApi.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}                  
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}    

